### ISSUE TITLE
Filter log entry is blocked and allowed

### ISSUE THREAD

**Issue by chrishub188** [blokadaorg/six-ios#1]
## Steps to reproduce
1. Got to Blokada-Cloud web dashboard blocklists  
2. Select 1host Pro Wildcard filter (not available in the App) and disable every other filter list
3. Trigger host e.g. api.eu-west-1.aiv-delivery.net

### Expected behavior
Host is listed in activity as allowed or blocked

### Actual behavior
Host is listed in activity as blocked and allowed

### Device information
* iPhone 13 mini
* Blokada 23.1.1 (Cloud)
![IMG_4944](https://github.com/blokadaorg/six-ios/assets/63286554/cf9b80ba-c85e-44e0-811d-e44fa6345853)

**Comment by balboah** [comment]
Let's reassess this issue after the fix for #2 has been rolled out.

If you still see this occurring, please don't hesitate to reopen the ticket. Your feedback is appreciated
