### ISSUE TITLE
1host Pro wildcard filter is blocking Apple domains

### ISSUE THREAD

**Issue by chrishub188** [blokadaorg/six-ios#2]
## Steps to reproduce
1. Got to Blokada-Cloud web dashboard blocklists  
2. Select 1host Pro Wildcard filter (not available in the App) and disable every other filter list
3. Trigger host e.g. cl4.apple.com, cl3.apple.com, cl2.apple.com, configuration.apple.com

### Expected behavior
Host is allowed 

### Actual behavior
Host is blocked 

### Additional information
The hosts listed are not included in 1host Pro wildcard filters.

https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/wildcards.txt

### Device information
* iPhone 13 mini
* Blokada 23.1.1 (Cloud)
![IMG_D3C6D9C7A63A-1](https://github.com/blokadaorg/six-ios/assets/63286554/097a1a93-986c-4844-9ebb-c48008665b40)

**Comment by balboah** [comment]
Thank you for the detailed report.

This as a valid issue and we will work on fixing it in coming days, stay tuned for updates!

**Comment by balboah** [comment]
I'm pleased to inform you that the issue has been addressed. As of now, you should no longer experience this issue.

Thank you once again for bringing this to our attention!
