### ISSUE TITLE
Blokada is displaying an ID string instead of the blocklist name in the activity log entries.

### ISSUE THREAD

**Issue by chrishub188** [blokadaorg/six-ios#6]
## Steps to reproduce
1. Enable Blokada with multiple filter list, e.g. AdAway + 1Host Lite + OISD.
2. Go to “Activity”
3. Tab on any red entry that is blocked.

### Expected behavior
Next to the red shield icon, the message appears, “_This request has been blocked because it's present on the *OISD*  blocklist._”
(or whatever filter list is the blocking reason)

### Actual behavior
Next to the red shield icon, the message appears, “_This request has been blocked, because it's present on the
*03c351a2112a6633572fd2783f.._”

### Additional information
The ID string changes based on the filter lists selected and the blocking reason. Occasionally, the name shows up, but mostly it's that long ID string. The behavior is the same for all entries. If the entry is on the custom block list, it is always displayed correctly. 

### Device information
* iPhone 13 mini
* Blokada 23.3.4 (Cloud)

![IMG_5966](https://github.com/blokadaorg/six-ios/assets/63286554/e68d7904-8b83-4b81-8a57-fbb61bc41544)
![IMG_5972](https://github.com/blokadaorg/six-ios/assets/63286554/454b28a1-f403-4ed2-b2e4-2ddf99e72e58)
![IMG_5965](https://github.com/blokadaorg/six-ios/assets/63286554/48395c1d-8ae2-4ce0-855b-7c5d88c2123a)

**Comment by balboah** [comment]
Thank you for your detailed report, we will have a look at this!

**Comment by kar** [comment]
To be verified in the upcoming 24.x.x release.

**Comment by balboah** [comment]
@chrishub188 is this issue still occurring for you in the latest version?

**Comment by chrishub188** [comment]
The issue is fixed with the latest version.
