### ISSUE TITLE
Blokada OISD filter are outdated 

### ISSUE THREAD

**Issue by chrishub188** [blokadaorg/six-ios#7]
OISD has 3 different lists:
- oisd small 
- oisd big 
- oisd nsfw

See: https://oisd.nl/setup

Blokada offers the three configurations: 
- Basic (Wildcards)
- Extra (Wildcards)
- Light

Suggested Configuration:
- oisd small (Wildcards)
- oisd big (Wildcards)

![IMG_5974](https://github.com/blokadaorg/six-ios/assets/63286554/9da2553e-c851-4844-a027-a1a9345ec122)
![Screenshot 2024-06-02 at 16-25-20 oisd Set up](https://github.com/blokadaorg/six-ios/assets/63286554/8fb23e81-2426-4477-bb5c-97620c46c5b6)

**Comment by balboah** [comment]
This should have been resolved in the latest version available on google play.

Thank you for the report!
